export_site = "DM-Akron"
nb_api_url = 'https://demo.netbox.dev'
nb_api_token = '1097d9f95484b207b84bdcabcf509c8208593a49'
export_device_roles = ["router", "core-switch", "access-switch", "distribution-switch", "tor-switch"]

